
export const planeTicket = [
  {
    id: 1,
    name: "بویینک 737",
    logo: "/image/SahaAir.svg",
    campony: "ساها ایر",
    icon: <smallPlane width={18} height={16} color="currentColor" />,
    start: "00:45",
    finish: "02:10",
    available: true,
    capicity: 9,
    price: 3402500,
  },
  {
    id: 2,
    name: "فوکر 100",
    logo: "/image/Aseman.svg",
    campony: "آسمان",
    icon: <smallPlane width={18} height={16} color="currentColor" />,
    start: "06:00",
    finish: "07:25",
    available: false,
    capicity: 0,
    price: 3402500,
  },
  {
    id: 3,
    name: "بی آیی 106",
    logo: "/image/Mahan.svg",
    campony: "ماهان",
    icon: <smallPlane width={18} height={16} color="currentColor" />,
    start: "11:45",
    finish: "13:10",
    available: true,
    capicity: 2,
    price: 4402500,
  },
];
