import HotelPage from "@/components/template/HotelPage";
import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "رزور بلیط هتل",
  description: "Generated by create next app",
};
function page() {
  return <HotelPage />;
}

export default page;
