import MyTicket from "@/components/template/MyTicket";
import React from "react";

import { Metadata } from "next";
export const metadata: Metadata = {
  title: "بلیط های من",
  description: "Generated by create next app",
};
function page() {
  return <MyTicket />;
}

export default page;
