import type { Metadata } from "next";
import "./globals.css";
import "@/styles/iranSans.css";
import Layout from "@/components/layout/Layout";

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "مستر بلیط ، سامانه اینترنتی رززو بلیط",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="bg-gray-200 font-iranSans">
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
