import BusPage from "@/components/template/BusPage";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "رزور بلیط اتوبوس",
  description: "Generated by create next app",
};
function page() {
  return <BusPage />;
}

export default page;
