import Services from "@/components/template/Services";
import React from "react";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "پروفایل",
  description: "Generated by create next app",
};

function page() {
  return <Services />;
}

export default page;
