import TaxiPage from "@/components/template/TaxiPage";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "رزور بلیط تاکسی",
  description: "Generated by create next app",
};

function page() {
  return <TaxiPage />;
}

export default page;
