import AirPlanePage from "@/components/template/AirPlanePage";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "رزور بلیط هواپیما",
  description: "Generated by create next app",
};

function page() {
  // console.log("wating for connection ...");
  return <AirPlanePage />;
}

export default page;
