import ProfilrPage from "@/components/template/ProfilrPage";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "پروفایل",
  description: "Generated by create next app",
};
function page() {
  return <ProfilrPage />;
}

export default page;
