import TrainPage from "@/components/template/TrainPage";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "رزور بلیط قطار ",
  description: "Generated by create next app",
};

function page() {
  return <TrainPage />;
}

export default page;
